Repository sessac-3rd-team-A/FE, pull requests merged in 2023-12, with the labels that each got.

#22 Profile footer/#4
  package-lock.json
  package.json
  public/images/profileMenu_1.svg
  public/images/profileMenu_2.svg
  public/images/profileMenu_3.svg
  public/images/profileMenu_icon1.svg
  public/images/profileMenu_icon2.svg
  public/images/profileMenu_icon3.svg
  public/images/profileShop_background.jpg
  public/profile/blueCircle.png
  public/profile/money-sack.png
  public/profile/myShop_background.jpg
  public/profile/person.png
  public/profile/settings.png
  public/tempFile.jpg
  src/app/layout.tsx
  src/app/profile/myShop/page.tsx
  src/containers/Profile/myShop.tsx
  src/containers/common/footer.tsx
  src/containers/common/profileFooter.tsx
  src/containers/common/profileMenu.tsx
  src/containers/myShop.tsx
  src/styles/profile/myShop.scss
  src/styles/profile/profileFooter.scss
  src/styles/profile/profileMenu.scss
Labels: UI/UX

#30 feat: profileMenuBar 최종 css/ link 수정 예정
  package-lock.json
  src/containers/common/profileMenu.tsx
  src/styles/profile/profileMenu.scss
Labels: UI/UX

#41 Setting page1/#39
  package-lock.json
  package.json
  public/images/profile_background2.svg
  src/app/profile/myShop/page.tsx
  src/app/profile/setting/error.tsx
  src/app/profile/setting/page.tsx
  src/containers/Profile/myShop.tsx
  src/containers/Profile/setting.tsx
  src/styles/profile/myShop.scss
  src/styles/profile/setting.scss
  src/types/index.d.ts
Labels: enhancement, UI/UX

#43 feat: account page css처리 및 form data 작업 완료
  src/app/profile/account/error.tsx
  src/app/profile/account/page.tsx
  src/app/profile/myShop/page.tsx
  src/app/profile/page.tsx
  src/containers/Profile/setting.tsx
  src/containers/mypage/EmoCalendar.tsx
  src/containers/mypage/diaryModal.tsx
  src/containers/mypage/index.tsx
  src/containers/mypage/myShop.tsx
  src/containers/mypage/profileMenu.tsx
  src/containers/mypage/setting.tsx
  src/containers/mypage/settingForm.tsx
  src/styles/profile/setting.scss
  src/styles/profile/settingForm.scss
Labels: enhancement, UI/UX

#49 profileMenu바 고정 및 link먹이는 중!!
  src/app/profile/my-shop/error.tsx
  src/app/profile/my-shop/loading.tsx
  src/app/profile/my-shop/page.tsx
  src/containers/profile/profileMenu.tsx
  src/containers/profile/setting.tsx
  src/containers/profile/settingForm.tsx
  src/styles/profile/myShop.scss
  src/styles/profile/profileMenu.scss
  src/styles/profile/setting.scss
Labels: fix, UI/UX

#72 feat: my-shop 페이지 css
  src/containers/Profile/myShop.tsx
  src/styles/profile/myShop.scss
  src/types/index.d.ts
Labels: UI/UX

#116 feat: accountAPI 완료
  package.json
  src/containers/Profile/account.tsx
  src/containers/Profile/myShop.tsx
  src/styles/profile/accountForm.scss
  src/styles/profile/myShop.scss
  src/types/index.d.ts
Labels: fix, refactor, UI/UX

#141 fix: README 수정(#126)
  README.md
Labels: documentation, fix
